# Generated by Django 5.2 on 2025-05-11 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('icona', models.ImageField(blank=True, null=True, upload_to='media/imgsrc/')),
                ('description', models.TextField()),
                ('condition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Autore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('death_date', models.DateField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/imgsrc/')),
            ],
        ),
        migrations.CreateModel(
            name='Opera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/imgsrc/')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sitomuseo.autore')),
            ],
        ),
        migrations.CreateModel(
            name='Crossword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=200)),
                ('matrix', models.JSONField()),
                ('autore', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sitomuseo.autore')),
                ('opera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sitomuseo.opera')),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('icona', models.ImageField(blank=True, null=True, upload_to='media/imgsrc/')),
                ('hash', models.CharField(max_length=257)),
                ('achievements', models.ManyToManyField(to='sitomuseo.achievement')),
                ('crosswords', models.ManyToManyField(to='sitomuseo.crossword')),
            ],
        ),
    ]
