# Generated by Django 4.2.11 on 2025-04-14 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitomuseo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('birth_date', models.PositiveIntegerField(blank=True, null=True)),
                ('death_date', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='opera',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/imgsrc/'),
        ),
        migrations.AlterField(
            model_name='opera',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sitomuseo.autore'),
        ),
    ]
