# Generated by Django 4.2.11 on 2025-05-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitomuseo', '0002_achievement_autore_alter_opera_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossword',
            name='matrix',
            field=models.JSONField(default='[]'),
            preserve_default=False,
        ),
    ]
