# Generated by Django 4.2.11 on 2025-04-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitomuseo', '0002_autore_alter_opera_image_alter_opera_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autore',
            name='description',
            field=models.TextField(),
        ),
    ]
