# Generated by Django 4.2.11 on 2025-04-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitomuseo', '0003_alter_autore_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='autore',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/imgsrc/'),
        ),
        migrations.AddField(
            model_name='autore',
            name='nation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='autore',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autore',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
